### ISSUE TITLE
Build Warning on Angular10

### ISSUE THREAD

**Issue by Qsaws** [Cordobo/angularx-qrcode#120] opened 2021-03-04 17:38 UTC
We get these warnings on build after an upgrade to Angular10.

```
WARNING in ../node_modules/angularx-qrcode/fesm2015/angularx-qrcode.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Any chance for this to be fixed?

**Comment by sovushka-utrom** [comment] 2021-03-12 11:03
Also get this warning for Angular 10: 
```
'qrcode' is not a known element:
1. If 'qrcode' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.ng
Can't bind to 'qrdata' since it isn't a known property of 'qrcode'.ng
```

**Comment by gravyplaya** [comment] 2021-03-23 06:10
As stated in the link in the error code.
add the line below to your angular.json 
`            "allowedCommonJsDependencies": [
              "qrcode"
            ]`

**Comment by pauloneill** [comment] 2021-04-07 03:14
I'm getting this issue with both Angular 10 AND 11:

`Error: src/app/jobs/jobs-swing-tag/jobs-swing-tag.component.html:5:13 - error NG8002: Can't bind to 'qrdata' since it isn't a known property of 'qrcode'.

5     <qrcode [qrdata]="'A simple string'" [size]="256" [level]="'M'"></qrcode>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I've added the allowedCommonJsDependencies line above and still the same error.

I have created a standalone version but wondered if there's an easy way to determine why this error is occurring without having to compare different projects line by line.... you know, like a debug or verbose switch somewhere?
(the ng serve --verbose command gives me TOO MUCH information to decypher... -_- )

TIA

**Comment by foramkumar-parekh** [comment] 2021-04-28 05:57
> We get these warnings on build after an upgrade to Angular10.
> 
> ```
> WARNING in ../node_modules/angularx-qrcode/fesm2015/angularx-qrcode.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
> ```
> 
> Any chance for this to be fixed?

Can we have a fix for this, so we do not have to add it into _allowedCommonJsDependencies_?

**Comment by Qsaws** [comment] 2021-07-21 07:04
So no fix in sight?

**Comment by Cordobo** [comment] 2021-12-30 13:30
No, this won't be fixed for version <= 10 as there is an easy workaround available.

Please open a new issue with a minimal working app so I may reproduce the issue. Thank you!

**Closed by Cordobo** 2021-12-30 13:30 UTC

**Comment by MShekow** [comment] 2022-01-05 09:16
The proposed fix here is a "sweep problem under the rug" work around. The underlying problem is that `angularx-qrcode` uses `qrcode` which itself does not support ESM import-mode, and won't do so anytime soon because the core maintainer is not interested in doing it themselves (see corresponding [ticket](https://github.com/soldair/node-qrcode/issues/236)).

**Comment by Cordobo** [comment] 2022-01-05 20:06
I commented on the underlying issue here #110 in more detail a while ago
