### ISSUE TITLE
Uncaught ReferenceError: global is not defined, After installation to Angular 9 app

### ISSUE THREAD

**Issue by aelagawy** [Cordobo/angularx-qrcode#79] opened 2020-04-24 22:04 UTC
Uncaught ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/qrcode/lib/core/reed-solomon-encoder.js (reed-solomon-encoder.js:3)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/qrcode/lib/core/qrcode.js (qrcode.js:10)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/qrcode/lib/browser.js (browser.js:4)
    at __webpack_require__ (bootstrap:79)
    at Module../node_modules/angularx-qrcode/__ivy_ngcc__/fesm2015/angularx-qrcode.js (angularx-qrcode.js:1)
    at __webpack_require__ (bootstrap:79)

**Comment by Cordobo** [comment] 2020-04-25 10:03
Hi @aelagawy ,

more information would be appreciated to provide support :-) You could provide a stripped down repo of your app so someone can reproduce your error.

Just in case, there is a working demo app here, which I use to test the lib with the latest angular versions, including Angular 9:
https://github.com/Cordobo/angularx-qrcode-sample-app

**Comment by Cordobo** [comment] 2020-04-29 18:10
I'm closing this, please re-open if you still encounter the issue.

**Comment by EnriqueSampaio** [comment] 2020-04-29 20:52
I had the exact same problem. The project compiles without any error, but I can't render any page in the browser, and the Chrome dev console shows that same error stack trace.

I export QRCodeModule through a SharedModule which I import at all my application modules.

**Comment by Cordobo** [comment] 2020-04-29 21:29
Ok, sounds good, do you mind provide me with a sample repo?

**Comment by EnriqueSampaio** [comment] 2020-04-30 00:47
It looks like the problem is about using Node.js specific packages in Angular projects running on browser only. Searching aroung I found a lot of similar errors in  other Angular libraries.

The workaround is adding this to your polyffils.ts file:
`(window as any).global = window;` 

The bug explanation (and workaroud) from angular-cli project:
[#8186](https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833)

**Comment by Cordobo** [comment] 2020-04-30 13:17
Ok, according to issue [#15954](https://github.com/angular/angular-cli/issues/15954) it's more like the issue is caused by angular-cli itself - and the known workaround is the one you posted `(window as any).global = window;`.

**Closed by Cordobo** 2020-04-30 13:17 UTC
Labels: question

**Comment by sshelake25** [comment] 2020-06-05 17:27
I tried posted work around. its  not working. I am facing same issue.

I have imported below pakages in one of service -

import { Injectable } from '@angular/core';
import * as enigma from 'enigma.js';
import WebSocket from 'ws';
import * as path from 'path';
import * as fs from 'fs';
import * as jwt from 'jsonwebtoken';

Service throwing error on ->  jsonwebtoken 
 

Even after adding , 
// Add global to window, assigning the value of window itself.
(window as any).global = window; 

Still getting error. please see below info

Angular CLI: 9.1.7
Node: 12.3.0
OS: darwin x64

Angular: 9.1.1
... animations, common, compiler, core, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.0.0
@angular/cli                       9.1.7
@angular/compiler-cli              9.1.9
@angular/elements                  9.0.1
@angular/forms                     9.1.9
@angular/http                      7.2.15
@ngtools/webpack                   9.1.7
@nguniversal/express-engine        7.1.1
@schematics/angular                9.1.7
@schematics/update                 0.901.7
ng-packagr                         9.0.0-rc.7
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.41.5
    

Error :

index.js:43 Uncaught ReferenceError: global is not defined
    at Object.../../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/safe-buffer/index.js (index.js:2)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/jws/lib/sign-stream.js (sign-stream.js:2)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/jws/index.js (index.js:2)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/jsonwebtoken/decode.js (decode.js:1)
    at __webpack_require__ (bootstrap:19)
../../node_modules/buffer/index.js @ index.js:43
__webpack_require__ @ bootstrap:19
../../node_modules/safe-buffer/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
../../node_modules/jws/lib/sign-stream.js @ sign-stream.js:2
__webpack_require__ @ bootstrap:19
../../node_modules/jws/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
../../node_modules/jsonwebtoken/decode.js @ decode.js:1
__webpack_require__ @ bootstrap:19
../../node_modules/jsonwebtoken/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
../../libs/rules/src/lib/enigma/enigma.service.ts @ selectors.ts:11
__webpack_require__ @ bootstrap:19
../../libs/rules/src/lib/performance/rules-performance.component.ts @ main.js:19389
__webpack_require__ @ bootstrap:19
../../libs/rules/src/lib/tfc-rules.module.ts @ tfc-rules.constants.ts:7
__webpack_require__ @ bootstrap:19
../../libs/rules/src/index.ts @ index.ts:1
__webpack_require__ @ bootstrap:19
./src/app/platform.module.ts @ platform.component.ts:17
__webpack_require__ @ bootstrap:19
./src/main.ts @ main.ts:2
__webpack_require__ @ bootstrap:19
0 @ main.ts:8
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83

**Comment by Cordobo** [comment] 2020-06-05 18:56
Hey @sshelake25

I don't see angularx-qrcode in your dependencies, it looks more like an issue with the package "jasonwebtoken". You might find help at there issue tracker:

https://github.com/auth0/node-jsonwebtoken/issues

If you think I'm wrong, please let me know.
