### ISSUE TITLE
qrcode types missing

### ISSUE THREAD

**Issue by sam-s4s** [Cordobo/angularx-qrcode#227] opened 2023-09-12 02:41 UTC
I apologise, but it looks like my fix has broken it in a strange way. Obviously I'm missing something.

This types/node problem is the gift that keeps on giving, isn't it...

```
Error: node_modules/angularx-qrcode/lib/angularx-qrcode.component.d.ts:3:44 - error TS7016: Could not find a declaration file for module 'qrcode'. 'C:/blah/node_modules/qrcode/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/qrcode` if it exists or add a new declaration (.d.ts) file containing `declare module 'qrcode';`

3 import { QRCodeErrorCorrectionLevel } from "qrcode";
                                             ~~~~~~~~


Error: node_modules/angularx-qrcode/lib/types.d.ts:1:44 - error TS7016: Could not find a declaration file for module 'qrcode'. 'C:/blah/node_modules/qrcode/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/qrcode` if it exists or add a new declaration (.d.ts) file containing `declare module 'qrcode';`

1 import { QRCodeErrorCorrectionLevel } from "qrcode";
                                             ~~~~~~~~
```

Now the types/qrcode package is not being included in node_modules, which has solved the problem over the NodeJS.Timer for setTimeout, etc. so that's good...

But because `angularx-qrcode.component.d.ts` and `types.d.ts` are trying to use `QRCodeErrorCorrectionLevel`, which comes from qrcode (which imports the bad types/node) - it seems we are running into a problem.

I'm not sure what the solution is here... the first thing that comes to mind, though, is... could we just not export anything in the angularx-qrcode that uses anything from qrcode?
ie. have a local copy of `QRCodeErrorCorrectionLevel` in `types.d.ts`, like we do for `QRCodeElementType` and `QRCodeVersion` ?

Or another possible solution... because the `@types/qrcode` package is clearly made for a nodejs environment and not a browser environment (unlike angularx-qrcode, which is of course browser-based) - maybe it could be best to just avoid using it entirely? (ie. don't even pull `@types/qrcode` anywhere and just use it without typing?)

Sounds counter-intuitive, and I've never needed to do that before, but it's clear from looking at `@types/qrcode` that is was never meant to be used for browser :(

Again, apologies for my solution not working.

**Comment by Helveg** [comment] 2023-09-12 07:45
I encounter the same problem. Unless this project has previously solved this issue in another way and this is a regression, the solution is to add `@types/qrcode` to the dependencies of the package. See these [docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#packaging-dependent-declarations):

> If your type definitions depend on another package:
> * Don’t combine it with yours, keep each in their own file.
> * Don’t copy the declarations in your package either.
> * Do depend on the npm type declaration package if it doesn’t package its declaration files.

**Comment by sam-s4s** [comment] 2023-09-12 23:15
Yes indeed it seems like QRCodeErrorCorrectionLevel is the only thing that requires it.

Given the type library for qrcode is actually for the nodejs environment (not the web/browser) I hope we can avoid using it, as it contaminates the browser environment.

**Comment by Helveg** [comment] 2023-09-13 09:00
@sam-s4s, I don't see your problem with the `qrcode` library. It works perfectly fine in the browser, please see the docs: https://www.npmjs.com/package/qrcode under `Installation` > `Browser`. The problem is that the package doesn't provide its own typings, and if you import the type, you have to list the typing package `@types/qrcode` as a dependency.

**Comment by sam-s4s** [comment] 2023-09-15 00:58
> @sam-s4s, I don't see your problem with the `qrcode` library. It works perfectly fine in the browser, please see the docs: https://www.npmjs.com/package/qrcode under `Installation` > `Browser`.
> 
> The problem here is that the package doesn't provide its own typings, and if you import the types in this package, then this package has to list the typing package `@types/qrcode` as a dependency, not as a devDependency.

Yes, it works fine, but the types are incorrect - that type library is for use in nodejs, not browser.

For example, the node types override the browser types in the IDE, so settimeout reutnrs NodeJS.Timer, instead of number, which is incorrect.

For more information, see previous issue #223

**Comment by ywei390** [comment] 2023-11-20 07:14
Hi, is this issue resolved? or is there any solution?

**Comment by Cordobo** [comment] 2023-12-08 14:35
Fixed in version 17

**Closed** 2023-12-08 14:35 UTC
