### ISSUE TITLE
Plan for beeing supported by Server Side Rendering

### ISSUE THREAD

**Issue by M2Key** [Cordobo/angularx-qrcode#5] opened 2018-03-06 12:13 UTC
Is there any plan for make it compatible with SSR. 

Once I actived SSR, I received : 
NodeInvocationException: Prerendering failed because of error: ReferenceError: document is not defined

**Comment by Cordobo** [comment] 2018-03-15 21:34
Hello @M2Key,

from my perspective it looks like a cool feature, I will have a look into it.
Please feel free to provide sample code.

**Comment by Cordobo** [comment] 2018-03-23 09:18
@cslgxuchang 

Please provide some sample-code for me on a plunkr or jsfiddle.

**Comment by cslgxuchang** [comment] 2018-03-26 01:13
@Cordobo  use angularx-qrcode@1.0.2, my project use angular@4.0.0, when I run it with ssr, error "document is not defined"  in  angularx-qrcode@1.0.2 module .  I  have no idea to resolve it.

**Comment by cbernth** [comment] 2018-06-12 20:03
These few changes makes SSR work for me:

angularx-qrcode.component.ts:
```
import {
	ChangeDetectionStrategy,
	Component,
	ElementRef,
	Input,
	OnChanges,
	OnInit,
	SimpleChange,
	AfterViewInit,
	Inject,
	PLATFORM_ID
} from '@angular/core';

declare var require: any;
var QRCode: any = undefined;

import { isPlatformServer } from '@angular/common';

@Component({
	selector: 'qrcode',
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: ''
})

export class QRCodeComponent implements OnChanges, OnInit, AfterViewInit {

	/** @internal */
	@Input() public allowEmptyString: boolean = false;
	@Input() public colordark: string = '#000000';
	@Input() public colorlight: string = '#ffffff';
	@Input() public level: string = 'M';
	@Input() public hidetitle: boolean = false;
	@Input() public qrdata: string = '';
	@Input() public size: number = 256;
	@Input() public usesvg: boolean = false;

	public qrcode: any;

	constructor(
		public el: ElementRef,
		@Inject(PLATFORM_ID) private platformId: Object,
	) { }

	public ngOnInit() {
	}

	public ngAfterViewInit() {
		if (isPlatformServer(this.platformId)) {
			return;
		}
		else {
			if (!QRCode) {
				QRCode = require('qrcodejs2');
			}
			try {
				if (!this.isValidQrCodeText(this.qrdata)) {
					throw new Error('Empty QR Code data');
				}

				this.qrcode = new QRCode(this.el.nativeElement, {
					colorDark: this.colordark,
					colorLight: this.colorlight,
					correctLevel: QRCode.CorrectLevel[this.level.toString()],
					height: this.size,
					text: this.qrdata || ' ',
					useSVG: this.usesvg,
					width: this.size,
				});
			} catch (e) {
				console.error('Error generating QR Code: ' + e.message);
			}
		}
	}

	public ngOnChanges(changes: { [propertyName: string]: SimpleChange }) {
		if (!this.qrcode) {
			return;
		}

		const qrData = changes['qrdata'];

		if (qrData && this.isValidQrCodeText(qrData.currentValue)) {
			this.qrcode.clear();
			this.qrcode.makeCode(qrData.currentValue);
		}
	}

	protected isValidQrCodeText = (data: string): boolean => {
		if (this.allowEmptyString === false) {
			return !(typeof data === 'undefined' || data === '');
		}
		return !(typeof data === 'undefined');
	}

}
```

**Comment by taoyouh** [comment] 2018-12-31 15:21
Maybe a pull request and a new release on NPM?

**Comment by Dyabel03** [comment] 2019-02-07 02:27
Hi, I have installed two versions of this package (^1.2.4 and ^1.5.3) in differents proyects, but i´dont see if the code of @cbernth is all ready implemented, is that so in what version of the package can i see this code, please?

**Comment by Cordobo** [comment] 2019-02-07 20:13
Hi @Dyabel03

No, the code from @cbernth has not been integrated into the repo yet.

**Comment by Dyabel03** [comment] 2019-02-07 23:13
Hi, @Cordobo  thank you for your answer, currently I need this in my work so, do you have any plan to implement this anytime soon?... I really appreciate your effort in this project and I don´t wanna sound rude...thank you in advance.

P.S: Or if you know how I can implement this would also be helpful, I tried to use the code of @cbernth but when I execute the universal angular the same error occurs.

**Comment by alchemistt99** [comment] 2019-02-09 16:43
i need too for my work so, please could you help us to fix it for angular universal.
still same error when execute 😢

**Comment by Cordobo** [comment] 2019-02-11 14:07
@Dyabel03 @alchemistt99 PRs are more than welcome!

**Comment by KoIIIeY** [comment] 2019-06-07 15:35
/frontend/dist/server.js:226874
        var useSVG = document.documentElement.tagName.toLowerCase() === "svg";
                     ^

ReferenceError: document is not defined

not working in 1.5.3

**Comment by Cordobo** [comment] 2019-06-28 17:46
Thanks to code contributed by @cbernth and @ZhenhangTung, as of version 1.6.0, angularx-qrcode has fully implemented SSR support.

Closing this (please open another issue, if you encounter any)

**Comment by naumov-dev** [comment] 2019-07-15 11:05
I got 
```
        var useSVG = document.documentElement.tagName.toLowerCase() === "svg";
                     ^

ReferenceError: document is not defined
```
version 1.6.1

**Comment by Cordobo** [comment] 2019-07-15 14:27
Hi @naumov-dev, could you please provide a stripped down repo for me to reproduce?

**Comment by ZhenhangTung** [comment] 2019-07-22 13:37
@Cordobo Same thing happened to me. Here is my [PR](https://github.com/Cordobo/angularx-qrcode/pull/42), but I don't know why my changes don't exist anymore on the [dev branch](https://github.com/Cordobo/angularx-qrcode/commits/development), which has cost me several hours to find out the true problem. If you look at my [company's fork](https://github.com/udacity/angularx-qrcode), you will see the:
> This branch is 4 commits ahead, 4 commits behind Cordobo:master.

On your [master branch](https://github.com/Cordobo/angularx-qrcode/blob/master/src/components/angularx-qrcode/angularx-qrcode.component.ts#L34), my changes still don't exist.
Hope you could fix the problem soon. I'll just use the forked version for now.

**Comment by Cordobo** [comment] 2019-07-22 14:12
@ZhenhangTung Thanks for your investigation, I have a look into it

**Comment by Cordobo** [comment] 2019-07-22 20:29
@ZhenhangTung I have reapplied the PRs and released a fixed version 1.6.4. Thanks for your feedback!

**Closed by Cordobo** 2019-07-22 20:29 UTC
Labels: enhancement

**Comment by baywind2018** [comment] 2019-09-18 17:03
Is it possible to generate the QR code from a component? I want to display a smaller version on the page, but when the user clicks the image generated from qrdata (wrapped in an anchor), I'd like to let them download a larger version. Can that be done?

**Comment by ZhenhangTung** [comment] 2019-09-19 02:19
@baywind2018 Could you show some pseudocode to us? From my understanding, the easiest way is to generate 2 QR code and make the larger one `display: none`. When a user clicks the image, which is the smaller one, we actually download the larger one.
