### ISSUE TITLE
build error @2.1.0

### ISSUE THREAD

**Issue by mohamedaboelmagd** [Cordobo/angularx-qrcode#73] opened 2020-01-28 11:28 UTC
ERROR in ./node_modules/angularx-qrcode/fesm5/angularx-qrcode.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/mohamed/Desktop/careerograph/web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16599:21)

**Comment by lazmeister** [comment] 2020-02-03 22:28
Getting the same error

**Comment by lazmeister** [comment] 2020-02-03 23:03
Tried downgrading to 2.0.2, It looks like an issue not related to this package as others have the same error. Using another QR code generator library for now

**Comment by Cordobo** [comment] 2020-02-04 19:05
Did you try to update your dev dependencies in your package.json? The issue is most likely an error in the angular packages, please see [issue 69](https://github.com/Cordobo/angularx-qrcode/issues/69) for a solution.

I'm closing for now and add the "fixed" label, please re-open when you still encounter the issue.

**Closed by Cordobo** 2020-02-04 19:05 UTC
