### ISSUE TITLE
Setting the light color as the qr code color.

### ISSUE THREAD

**Issue by foramkumar-parekh** [Cordobo/angularx-qrcode#61] opened 2019-11-05 08:19 UTC
I am using below colours and every time, colorLight is used for QR code generation and colorDark is used as background-colour

> colorLight = #0080b9
>  colorDark = #ffffff

![image](https://user-images.githubusercontent.com/26627307/68191587-de0cab80-ffd5-11e9-8d1d-eaa9061d3f17.png)

Why is it behaving in this way? What is the way to fix it and get the colours in an expected manner?

I am using version 1.5.3

**Comment by Robhox** [comment] 2019-11-05 13:24
I think that the colors are working as intended and you inverted colors. I would bet your QR code is not scannable in the current state. You should try : 
colorLight = #ffffff
colorDark = #0080b9

**Comment by foramkumar-parekh** [comment] 2019-11-05 13:41
Well for some of my other colour combinations, the Light colour is #ffffff and the background is displayed as white. so I am expecting it to be a blue background and white QRcode colour.

Note: I am using version 1.5.3

**Comment by Robhox** [comment] 2019-11-05 15:21
I can ensure you that the colors work as intended. Please print the same QR code with colorLight and colorDark inverted and see by yourself that the two generated codes aren't the same.

**Comment by foramkumar-parekh** [comment] 2019-11-05 16:01
I tried inverting colors as well and got the same result.

That's the reason I have raised the issue

**Comment by foramkumar-parekh** [comment] 2019-11-06 08:02
@Cordobo would you like to share your thoughts on this?

**Comment by Cordobo** [comment] 2019-11-10 19:39
I haven't tried it (please attach a working repo if you want me to check it out) but as @Robhox mentioned, the code looks inverted - have a look at a working QR code and compare the squares in the corners with the one in your version.

I close this for now, please reopen and add a repo to reproduce the issue if it still exists

**Closed by Cordobo** 2019-11-10 19:39 UTC

**Comment by foramkumar-parekh** [comment] 2019-11-11 09:32
Please find below image with both the colour combinations. The light and dark colours are mentioned in the image itself. Hope this helps.
![image](https://user-images.githubusercontent.com/26627307/68576216-b7e28200-0493-11ea-8e0c-bc0d911a611d.png)
![image](https://user-images.githubusercontent.com/26627307/68576311-dc3e5e80-0493-11ea-8e42-55cd57a628df.png)

the code snippet used in my code is as below

`<qrcode #qrTag [qrdata]="userDetailStr" [level]="'M'" [colorlight]="colorLight" [colordark]="colorDark"
          [usesvg]="false"></qrcode>`

I need the QRcode in white and background in blue.

@Cordobo  I guess above will help you explain the problem.

**Comment by Cordobo** [comment] 2019-12-29 22:53
Fixed in Version 2.0.0
